# Generated by Django 5.0.2 on 2024-02-27 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pastores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='PastorPresidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Secretarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Tesoureiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_batismo', models.DateField(verbose_name='Data de Batismo')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Igrejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('pastores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pastores')),
            ],
        ),
    ]
