# Generated by Django 5.0.2 on 2024-02-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorpresidente',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
    ]
