# Generated by Django 5.0.2 on 2024-02-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_pastorpresidente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrejas',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='membros',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='membros',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pastorpresidente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='secretarios',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='secretarios',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tesoureiro',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tesoureiro',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
