# Generated by Django 5.0.2 on 2024-03-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_igrejas_email_alter_membros_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrejas',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='membros',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pastorpresidente',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='secretarios',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
    ]
