# Generated by Django 5.1.4 on 2025-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataformaigreja', '0015_membros_ativo_membros_nome_igreja_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='transferencia_membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igreja_origem', models.CharField(max_length=100)),
                ('igreja_destino', models.CharField(max_length=100)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaigreja.membros')),
            ],
        ),
    ]
