# Generated by Django 5.1.4 on 2025-04-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_transferencia'),
        ('plataformaTransferencias', '0001_initial'),
        ('plataformaigreja', '0016_delete_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaMembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateField(auto_now_add=True)),
                ('igreja_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='igreja.igreja')),
                ('igreja_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origem', to='igreja.igreja')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='plataformaigreja.membros')),
            ],
        ),
        migrations.DeleteModel(
            name='transferencia_membros',
        ),
    ]
