# Generated by Django 5.1.4 on 2025-04-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0005_delete_transferencia'),
        ('plataformaTransferencias', '0002_transferenciamembros_delete_transferencia_membros'),
        ('plataformaigreja', '0016_delete_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('igreja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igreja_destino', to='igreja.igreja')),
                ('igreja_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igreja_origem', to='igreja.igreja')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaigreja.membros')),
            ],
        ),
    ]
