# Generated by Django 5.1.4 on 2025-07-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaTransferencias', '0003_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='igreja_origem',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='igreja_destino',
            field=models.CharField(max_length=255),
        ),
    ]
