# Generated by Django 5.1.4 on 2025-02-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='destino',
        ),
        migrations.AddField(
            model_name='oferta',
            name='descricao',
            field=models.CharField(default='Oferta Diversa', max_length=255),
        ),
    ]
