# Generated by Django 5.1.4 on 2025-02-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataformaigreja', '0014_remove_membros_layout_carteirinha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_dizimo', models.DateField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaigreja.membros')),
            ],
        ),
    ]
