# Generated by Django 5.1.4 on 2025-02-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformadizimos', '0001_initial'),
        ('plataformaigreja', '0014_remove_membros_layout_carteirinha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dizimo',
            new_name='Dizimos',
        ),
    ]
