# Generated by Django 5.1.4 on 2025-03-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilpastor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilPastor',
        ),
    ]
