# Generated by Django 5.1.4 on 2025-03-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
