# Generated by Django 5.1.4 on 2025-01-21 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Maculino')], max_length=1)),
                ('cpf', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
                ('endereco', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_membros')),
                ('data_cadastro', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('obs', models.TextField(max_length=200)),
                ('data_batismo', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('ativo', models.CharField(max_length=6)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
