# Generated by Django 5.1.4 on 2025-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='cargo',
            field=models.CharField(choices=[('A', 'Auxiliar'), ('C', 'Congregado'), ('Cr', 'Crianças'), ('Da', 'Diaconisa'), ('D', 'Diácono'), ('E', 'Evangelista'), ('J', 'Jovem'), ('M', 'Membro'), ('Mi', 'Missionário(a)'), ('Pr', 'Pastor'), ('P', 'Presbítero')], max_length=2),
        ),
    ]
