# Generated by Django 5.1.4 on 2025-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0002_alter_membros_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membros',
            name='idade',
        ),
        migrations.AlterField(
            model_name='membros',
            name='ativo',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='membros',
            name='cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membros',
            name='data_batismo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='membros',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membros',
            name='obs',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='membros',
            name='telefone',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
