# Generated by Django 5.1.4 on 2025-01-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0003_remove_membros_idade_alter_membros_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membros',
            name='ativo',
        ),
    ]
