# Generated by Django 5.1.4 on 2025-01-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0006_alter_membros_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membros',
            name='obs',
        ),
    ]
