# Generated by Django 5.1.4 on 2025-01-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0007_remove_membros_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membros',
            name='foto',
        ),
    ]
