# Generated by Django 5.1.4 on 2025-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0008_remove_membros_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_membros'),
        ),
    ]
