# Generated by Django 5.1.4 on 2025-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0009_membros_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='data_batismo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='membros',
            name='telefone',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
