# Generated by Django 5.1.4 on 2025-01-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0010_alter_membros_cpf_alter_membros_data_batismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/img_membros'),
        ),
    ]
