# Generated by Django 5.1.4 on 2025-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0012_alter_membros_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='layout_carteirinha',
            field=models.ImageField(blank=True, null=True, upload_to='layout_carteirinhas'),
        ),
    ]
