# Generated by Django 5.1.4 on 2025-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0013_membros_layout_carteirinha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membros',
            name='layout_carteirinha',
        ),
    ]
