# Generated by Django 5.1.4 on 2025-04-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0003_igreja_nome_igreja'),
        ('plataformaigreja', '0014_remove_membros_layout_carteirinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='nome_igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('igreja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igreja_destino', to='igreja.igreja')),
                ('igreja_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igreja_origem', to='igreja.igreja')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaigreja.membros')),
            ],
        ),
    ]
