# Generated by Django 5.1.4 on 2025-04-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaigreja', '0015_membros_ativo_membros_nome_igreja_transferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transferencia',
        ),
    ]
