# Generated by Django 5.1.4 on 2025-02-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_vencimento', models.DateField()),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contas_a_pagar/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
