# Generated by Django 5.1.4 on 2025-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacontas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
