# Generated by Django 5.1.4 on 2025-02-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacontas', '0004_contapagar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Paga')], default=0),
        ),
    ]
