# Generated by Django 5.1.4 on 2025-02-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacontas', '0005_alter_contapagar_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento']},
        ),
    ]
