# Generated by Django 5.1.4 on 2025-02-19 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacontas', '0007_alter_contapagar_options_remove_contapagar_pastor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento']},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='pastor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='contas_a_pagar/'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
