# Generated by Django 5.1.4 on 2025-03-22 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_igreja/', verbose_name='Logo da Igreja')),
                ('fundo_carteirinha', models.ImageField(blank=True, null=True, upload_to='fundos_carteirinha/', verbose_name='Fundo da Carteirinha')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Pastor')),
                ('secretario', models.CharField(max_length=255, unique=True, verbose_name='Nome do Secretário')),
                ('tesoureiro', models.CharField(max_length=255, unique=True, verbose_name='Nome do Tesoureiro')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
