# Generated by Django 5.1.4 on 2025-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Pastor'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='secretario',
            field=models.CharField(max_length=255, verbose_name='Nome do Secretário'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='tesoureiro',
            field=models.CharField(max_length=255, verbose_name='Nome do Tesoureiro'),
        ),
    ]
