# Generated by Django 5.1.4 on 2025-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_alter_igreja_nome_alter_igreja_secretario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='nome_igreja',
            field=models.CharField(default='Igreja', max_length=255, verbose_name='Nome da Igreja'),
        ),
    ]
