# Generated by Django 5.1.4 on 2025-04-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_transferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transferencia',
        ),
    ]
